wheelctrl_ros2:
  ros__parameters:
    robot_param:
      name: "Elephant Robot"

    moving_wheel:
      type_name: "omni"
      radius: 0.051
      quantity: 3
      loop_rate: 200.0
      gear_ratio: 1.0
      distance: [0.39138,0.39138,0.39138]
      arguments: [30.0,150.0,270.0]
      wheel_name: ["FL","B","FR"]

    measuring_wheel:
      type_name: "omni"
      radius: 0.051
      quantity: 3
      loop_rate: 200.0
      gear_ratio: 1.0
      distance: [0.39138,0.39138,0.39138]
      arguments: [30.0,150.0,270.0]
      wheel_name: ["FL","B","FR"]

