wheelctrl_ros2:  
  ros__parameters:
    robot_param:
      name: "Rabbit Robot"
    
    moving_wheel:
      type_name: "steering"
      radius: 0.051
      quantity: 4
      loop_rate: 200.0
      gear_ratio: 1.0
      gear_ratio_horizonal: 1.0
      coordinates: "cartesian"
      length_x: 0.5
      length_y: 0.5
      wheel_name: ["FR","BR","FL","BL","FR_S","BR_S","FL_S","BL_S"]
    
    measuring_wheel:
      type_name: "steering"
      radius: 0.051
      quantity: 4
      loop_rate: 200.0
      gear_ratio: 1.0
      gear_ratio_horizonal: 1.0
      coordinates: "cartesian"
      length_x: 0.5
      length_y: 0.5
      wheel_name: ["FR","BR","FL","BL","FR_S","BR_S","FL_S","BL_S"]
